name: Update README

on:
  workflow_dispatch: # Trigger manually
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to v3

      # Step 2: Generate dynamic content or update README
      - name: Update README content
        run: |
          # Example: Add last updated timestamp to README
          echo -e "\n---\n\n**Last Updated:** $(date +"%Y-%m-%d %H:%M:%S")" >> README.md

      # Step 3: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Automated README update"
          git push
